"""departure_date, receive_date in Invoice model

Revision ID: 140d716c06a7
Revises: da18a4e8da81
Create Date: 2019-10-05 15:41:01.233669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140d716c06a7'
down_revision = 'da18a4e8da81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('departure_date', sa.DateTime(), nullable=True))
    op.add_column('invoice', sa.Column('receive_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'receive_date')
    op.drop_column('invoice', 'departure_date')
    # ### end Alembic commands ###
